apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        envFrom:
        - secretRef:
            name: ecom-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ecom-backend
  ports:
  - port: {{ .Values.backend.port }}

