apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: ecom-frontend
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}
    nodePort: {{ .Values.frontend.nodePort }}

